#!/bin/bash

function llegeixConfig()
{
  if [ -f "$CONFIG/$rol" ]       #si no esta configuracio, entorn no existeix i cal crearlo
    then

        i=0
        while read -r line; do
            case "$i" in
                0)
                    IFS=',' read -r -a arrayProgrames <<< "$line"
                    ;;
                1)
                    direccioBashrc="$line"
                    ;;
                2)
                    tempsEntorn="$line"
                    ;;
                3)
                    tempsHome="$line"
                    ;;
                4)
                    publishPorts="$line"
                        ;;

                5)
    		    exposedPorts="$line"
                        ;;

                6)
                        bridged="$line"
                        ;;
                7)
                        cpu="$line"
                        ;;
                8)
                        cpuShares="$line"
                        ;;
                9)
                        memFisica="$line"
                        ;;
                10)
                        memSwap="$line"
			;;
                *)
                    ;;
            esac
            i=$((i+1))

        done < "$CONFIG/$rol"
    else

echo "$CONFIG/$rol"
        echo "Error, no existeix el fitxer configuracio del rol: $conf"
        exit
    fi
}


#COMENÇA SCRIPT
#----------------------------
echo "Hola"
fraseGroups="groups $user"
grups="$($fraseGroups)"
array=( $grups )
rol="${array[2]}"
echo "AAA $rol"

CONFIG=/data/users/config

llegeixConfig
cp="$(nproc)"

if (( $(echo "$cp <  $cpu" |bc -l) )); then
  echo "Error, there isn't enough CPU!"
fi
if [ ! "$(docker ps -a | grep $USER)" ]; then

	docker create -i -t --user "$USER" --name="$USER"  -p "$exposedPorts"  -m "$memFisica" --memory-swap "$memSwap" medium /bin/bash
        echo "NO EXISTEIX"

else
	echo "EXISTEIX"
fi

sudo docker exec -it "$USER" "$1:x:0001:1001::/home/$1:/bin/bash1" > /etc/passwd                                            ##PREGUNTAAR


docker exec -it "$USER" cd /home/
mv mediumImage "$USER"
chown -R "$USER" "$USER"



docker attach "$USER"

docker exec -it "$USER" service /home/.bashrc                                            ##PREGUNTAAR
docker exec -it "$USER" cd /home/
mv mediumImage "$USER"
chown -R "$USER" "$USER"
docker start "$USER"








#Limitar memoria fisica i swap==  -m i --memory-swap
#Limitar CPU -c 512/1024/...  --cpu-shares


