#!/bin/bash

function llegeixConfig()
{
  if [ -f "$CONFIG/$rol" ]       #si no esta configuracio, entorn no existeix i cal crearlo
    then

        i=0
        while read -r line; do
            case "$i" in
                0)
                    IFS=',' read -r -a arrayProgrames <<< "$line"
                    ;;
                1)
                    direccioBashrc="$line"
                    ;;
                2)
                    tempsEntorn="$line"
                    ;;
                3)
                    tempsHome="$line"
                    ;;
                4)
                    publishPorts="$line"
                        ;;

                5)
    		    exposedPorts="$line"
                        ;;

                6)
                        bridged="$line"
                        ;;
                7)
                        cpu="$line"
                        ;;
                8)
                        cpuShares="$line"
                        ;;
                9)
                        memFisica="$line"
                        ;;
                10)
                        memSwap="$line"
			;;
                *)
                    ;;
            esac
            i=$((i+1))

        done < "$CONFIG/$rol"
    else

echo "$CONFIG/$rol"
        echo "Error, no existeix el fitxer configuracio del rol: $conf"
        exit
    fi
}


#COMENÇA SCRIPT
#----------------------------

fraseGroups="groups $user"
grups="$($fraseGroups)"
array=( $grups )
rol="${array[2]}"


CONFIG=/data/users/config

llegeixConfig
cp="$(nproc)"

if (( $(echo "$cp <  $cpu" |bc -l) )); then
  echo "Error, there isn't enough CPU!"
fi
if [ ! "$(docker ps -a | grep $USER)" ]; then
	case "$USER" in
		"datastore")
			docker create -i -t --user "$USER" --name="$USER" -m "$memFisica" --memory-swap "$memSwap" datastore /bin/bash
		;;

		"visitor")
                	docker create -i -t --user "$USER" --name="$USER" -m "$memFisica" --memory-swap "$memSwap" visitor /bin/bash
                ;;

		*)
                	docker create -i -t --user "$USER" --name="$USER" -p "$exposedPorts"  -m "$memFisica" --memory-swap "$memSwap" "$rol" /bin/bash
                ;;
	esac
        echo "NO EXISTEIX"

else
	echo "EXISTEIX"
fi

#docker exec -u root -it "$USER" "$1:x:0001:1001::/home/$1:/bin/bash1" > "$USER":/etc/passwd                                            ##PREGUNTAAR



docker start "$USER"

docker cp -a /etc/passwd "$USER":/etc/passwd

docker exec -u 0 -it "$USER" whoami

docker exec -u 0 -it "$USER" rm -rf "$USER":/home/mediumImage

#docker exec -u 0 -it "$USER" cd /home

docker cp -a  data/users/"$rol" "$USER":/home


docker attach "$USER"







#Limitar memoria fisica i swap==  -m i --memory-swap
#Limitar CPU -c 512/1024/...  --cpu-shares


docker exec -u 0 -it "$USER" cd /home/
#mv mediumImage "$USER"
#chown -R "$USER" "$USER"
#source /home/.bashrc

